h5_directory: /hps/nobackup/arl/chembl/tevfik/deep-apbs-data/pdbbind/box161
features:
  - electrostatic_grid
  - shape
  - atomic_donor
label: binding_site_in_dataset
training:
  early_stopping_patience: 60
  num_epochs: 300
  batch_size: 1
  accumulation_steps: 8
  learning_rate: 0.001
  weight_decay: 1.0e-05
  optimizer: adam
  scheduler:
    type: ReduceLROnPlateau
    factor: 0.2
    patience: 15
    mode: min
  loss:
    type: BCEDiceLoss
    alpha: 0.5
    smooth: 1.0
    pos_weight: 10
validation:
  batch_size: 1
  accumulation_steps: 8
datasets:
  test:
  - 1t7d
  - 4r75
  - 2fqt
  - 1dqn
  - 5gja
  - 5km9
  - 3fjg
  - 1sw2
  - 5tcj
  - 4gbd
  - 5yz2
  - 5vij
  - 1dy4
  - 1m48
  - 4non
  - 4jpy
  - 4d1j
  - 5f0f
  - 1h2k
  - 4pb2
  - 1wn6
  - 5ayt
  - 1pgp
  - 5ey0
  - 5vd2
  - 5d0r
  - 5mn1
  - 1rnt
  - 2v54
  - 2q8h
  - 6hh3
  - 5hjq
  - 4jal
  - 5uk8
  - 1r9l
  - 3aaq
  - 1n4k
  - 3e5a
  - 5ct2
  - 4pft
  - 6g35
  - 3ta0
  - 3p2e
  - 2vb8
  - 4dkp
  - 3kr4
  - 4eb8
  - 5oa2
  - 2i80
  - 5hwv
  - 3x00
  - 2vc9
  - 5h1u
  - 3hmp
  - 4o6w
  - 5v79
  - 4pf5
  - 5n1z
  - 5hcv
  - 1ua4
  - 4xu1
  - 1o1s
  - 1lnm
  - 3rlr
  - 4l9i
  - 4hws
  - 2e2p
  - 5f8y
  - 2w9h
  - 4da5
  - 2yhw
  - 5d6j
  - 4ezx
  - 5x62
  - 3ocz
  - 2vzr
  - 4e67
  - 5vi6
  - 5dnu
  - 4axd
  - 5tcy
  - 3arx
  - 4q19
  - 2wca
  - 4bc5
  - 2x6x
  - 1qaw
  - 3t1a
  - 5laq
  - 2zx7
  - 6mjf
  - 5yhe
  - 1wc1
  - 5dxt
  - 2jjb
  - 5sym
  - 2ews
  - 1l83
  - 5ko1
  - 4pqa
  - 3axz
  - 5kh3
  - 5fsx
  - 3tb6
  - 4h85
  - 1a4r
  - 4mo4
  - 5fnu
  - 4qdk
  - 5hbn
  - 1oba
  - 1ceb
  - 5ovx
  - 4b8y
  - 5t7s
  - 1kyv
  - 3wto
  - 5kbe
  - 3rm9
  - 4bcn
  - 6ayi
  - 2h21
  - 5ouh
  - 4keq
  - 2yfx
  - 5kly
  - 4q3t
  - 2gsu
  - 5wbm
  - 4loo
  - 1wuq
  - 2fxv
  - 4ieh
  - 2wjg
  - 2euk
  - 4c2v
  - 2vk6
  - 6gzd
  - 3nyd
  - 4qrh
  - 4ge1
  - 6cfc
  - 5hct
  - 4z2b
  train:
  - 5uv2
  - 1ajp
  - 6ckw
  - 5f1v
  - 1lgt
  - 4w97
  - 1dud
  - 1o5a
  - 4rpo
  - 3o56
  - 4d4d
  - 4psb
  - 1t4v
  - 2nnd
  - 5c2o
  - 4a7i
  - 4je7
  - 3r88
  - 6h5x
  - 1fch
  - 5ih9
  - 3eeb
  - 3e3c
  - 4m3p
  - 4f6u
  - 2amt
  - 1wht
  - 5twj
  - 1qk3
  - 3alt
  - 1tq4
  - 1mfi
  - 2xde
  - 2we3
  - 2bvd
  - 3ipu
  - 3m6r
  - 5l7h
  - 5wuk
  - 6f9g
  - 2ovv
  - 3lvw
  - 3o5n
  - 5yft
  - 2i3h
  - 4ykk
  - 3ocp
  - 4btk
  - 4ufi
  - 4iid
  - 2vpe
  - 4fl2
  - 4hzm
  - 4v24
  - 4mjp
  - 2uy3
  - 5bv3
  - 3sr4
  - 1q5k
  - 3gdt
  - 5mlj
  - 5upe
  - 3uw4
  - 1ydk
  - 4cd4
  - 3v78
  - 2w47
  - 1x38
  - 3h78
  - 2gvv
  - 2wq5
  - 5mgj
  - 1b55
  - 3cke
  - 3gbe
  - 3wgg
  - 3m3z
  - 3aqt
  - 6f05
  - 2yz3
  - 1nki
  - 4bps
  - 1kjr
  - 4aq6
  - 1xk9
  - 3ebl
  - 1kdk
  - 2uxi
  - 1h0a
  - 4wkn
  - 4c1y
  - 3hit
  - 3uzj
  - 2v2v
  - 4e1k
  - 4cu8
  - 3hp9
  - 4oks
  - 5var
  - 4hym
  - 4b5w
  - 4ih3
  - 4us3
  - 6std
  - 3o75
  - 3qox
  - 4rlu
  - 4bt3
  - 5mmg
  - 1fao
  - 4agq
  - 3e12
  - 3s6t
  - 2v88
  - 2gss
  - 3rf5
  - 2reg
  - 4kzu
  - 4i7l
  - 3jrs
  - 3w5n
  - 5t8p
  - 4jkw
  - 2v57
  - 1duv
  - 1z4o
  - 4u70
  - 6eq1
  - 2r75
  - 3rdo
  - 4aci
  - 3dzt
  - 5l8y
  - 2ydt
  - 4zyf
  - 4duh
  - 6cvv
  - 4ynl
  - 5o58
  - 2hzy
  - 1uz4
  - 4wov
  - 3f3d
  - 1e3v
  - 5tbm
  - 3k4q
  - 6hsh
  - 5ndf
  - 5c5t
  - 4ymh
  - 4dmw
  - 5gmh
  - 1swg
  - 3dgo
  - 5n18
  - 3pce
  - 5h8e
  - 2q8z
  - 6gwr
  - 1nja
  - 1gyy
  - 4zme
  - 2j7b
  - 6ftp
  - 2uyq
  - 4z07
  - 6fhk
  - 4de0
  - 4dv8
  - 5we9
  - 1w5y
  - 5m17
  - 5oku
  - 5gsa
  - 3exe
  - 4zeb
  - 3q6z
  - 5m28
  - 2v58
  - 1qbq
  - 5ltn
  - 3upv
  - 4lxz
  - 2qpu
  - 4nbn
  - 2wuf
  - 3ao4
  - 4u0w
  - 5evd
  - 4bks
  - 4up5
  - 1nw5
  - 4rlt
  - 3t60
  - 2vfk
  - 4der
  - 5f74
  - 2vnp
  - 5hwu
  - 3k00
  - 6cwn
  - 5ahw
  - 2fxu
  - 5gof
  - 5c3p
  - 5mek
  - 2hmu
  - 3f8c
  - 2vhj
  - 4b1j
  - 1szd
  - 2r58
  - 5wqc
  - 1qji
  - 5z7b
  - 5mrp
  - 4oct
  - 2uz9
  - 1ii5
  - 3k37
  - 4aq4
  - 3kyq
  - 2cht
  - 3hv8
  - 4ncn
  - 5fhm
  - 4fht
  - 2o4j
  - 3p8p
  - 4x3k
  - 6euw
  - 4nku
  - 5irr
  - 5i3a
  - 1pot
  - 2wzf
  - 2clk
  - 4dq2
  - 5oha
  - 3vx3
  - 4fai
  - 3ewc
  - 3vjc
  - 1txr
  - 1yfz
  - 3vvy
  - 3kgq
  - 5m7u
  - 4rdn
  - 4o2b
  - 1mai
  - 3acx
  - 1i1e
  - 4qij
  - 4ara
  - 4ts1
  - 5kby
  - 2vo4
  - 3r1v
  - 1k27
  - 1xd0
  - 5f2u
  - 5hi7
  - 2tpi
  - 4e70
  - 2ydw
  - 5vo1
  - 6ht1
  - 2vw2
  - 4zb6
  - 4u43
  - 5c1m
  - 3o7u
  - 5k8s
  - 1dar
  - 4xxh
  - 5m04
  - 3fzy
  - 4j48
  - 1ogg
  - 3su3
  - 5yl2
  - 4kxn
  - 6edr
  - 3w07
  - 1ws4
  - 3qt6
  - 3vhk
  - 4yc0
  - 4y2q
  - 3c39
  - 5i1q
  - 4omj
  - 2aac
  - 5h5f
  - 2xn5
  - 2p4s
  - 3hcm
  - 2xg9
  - 1ec9
  - 3l4y
  - 3m8u
  - 1ik4
  - 4zow
  - 4kax
  - 5d3x
  - 2xpk
  - 3q1x
  - 5jzi
  - 3ozr
  - 3juk
  - 3hig
  - 5meh
  - 4oiv
  - 1drv
  - 2xn3
  - 4q93
  - 4km0
  - 6hlx
  - 1m7y
  - 3d2e
  - 3b7r
  - 4b9z
  - 5duw
  - 2qbu
  - 4zcs
  - 3pwk
  - 3po1
  - 4b6o
  - 2a8g
  - 3f37
  - 5n99
  - 5ulp
  - 3a1e
  - 4lj8
  - 1erb
  - 6bm5
  - 3iss
  - 4bb9
  - 5ave
  - 3hb4
  - 1xap
  - 3ppm
  - 3mi2
  - 6f1j
  - 1u0g
  - 2vpo
  - 2r0h
  - 4zl4
  - 6bhv
  - 4p3h
  - 6ezq
  - 1bq4
  - 3n1c
  - 6iiu
  - 5jhb
  - 4gah
  - 2xef
  - 2fmb
  - 3i73
  - 3tif
  - 2q7q
  - 3k4d
  - 2hjb
  - 4eu0
  - 2v25
  - 1wm1
  - 1pkx
  - 3g3r
  - 4l6t
  - 4zw6
  - 3fzn
  - 4ozj
  - 3u10
  - 4az5
  - 5nwi
  - 4ewn
  - 5lso
  - 3bxh
  - 4w9f
  - 2qtt
  - 2uyn
  - 5lyn
  - 4mss
  - 2e1w
  - 3sm2
  - 2oi2
  - 3aho
  - 3iob
  - 5vsj
  - 5ivy
  - 2jkp
  - 3lmk
  - 3v5p
  - 1b57
  - 2x09
  - 4kn0
  - 5n17
  - 2mas
  - 3uw5
  - 5d1r
  - 4cs9
  - 4csd
  - 5btx
  - 2wos
  - 3ga5
  - 4dcs
  - 2rcn
  - 3zq9
  - 2ylc
  - 3c2o
  - 4io7
  - 5kax
  - 5xpi
  - 3tzm
  - 3tf6
  - 4kzq
  - 4bqs
  - 3iw5
  - 6g9i
  - 3t01
  - 4ih6
  - 4qxo
  - 4oak
  - 5b2d
  - 1pvn
  - 5htl
  - 2ihj
  - 4jyc
  - 4j22
  - 4l4v
  - 3ies
  - 4do4
  - 4mre
  - 6g0z
  - 3zln
  - 1e2k
  - 5z99
  - 4p5z
  - 3mi3
  - 5g61
  - 5ito
  - 4oag
  - 3lp7
  - 2j27
  - 3t0x
  - 3ozj
  - 4umc
  - 3w9r
  - 4bqh
  - 3hww
  - 4muv
  - 5tef
  - 5tmp
  - 6eux
  - 1nfu
  - 1np0
  - 4lkk
  - 4cc5
  - 2a14
  - 4w9p
  - 1fzq
  - 5i7y
  - 5gs9
  - 3ccw
  - 4ido
  - 3re4
  - 3sfg
  - 4p6c
  - 1pa9
  - 6g2m
  - 4qnb
  - 2wzs
  - 3ip8
  - 1lyb
  - 3zi0
  - 2xp7
  - 4rfr
  - 3rv8
  - 4ksy
  - 6gvz
  - 4ocq
  - 3i51
  - 3egt
  - 2w8w
  - 4dsy
  - 5nw7
  - 1yvm
  validation:
  - 2v3d
  - 3bu1
  - 6eiz
  - 3f70
  - 3bex
  - 6b5q
  - 1x8j
  - 1vfn
  - 5vr8
  - 6bbx
  - 2haw
  - 2ccb
  - 3n9s
  - 3pju
  - 4ou3
  - 6cpw
  - 4ko8
  - 4q9o
  - 3f6g
  - 2yfa
  - 4br3
  - 2h6b
  - 1g85
  - 1grp
  - 1d9i
  - 6hai
  - 1xh5
  - 1r5y
  - 3cm2
  - 4kow
  - 6exs
  - 1uj5
  - 2ra6
  - 5m25
  - 3p7i
  - 5lz4
  - 5fcz
  - 1n4h
  - 4iuo
  - 3iae
  - 5op5
  - 1pfu
  - 2cli
  - 6h1u
  - 2xda
  - 4yb5
  - 1ssq
  - 5z5f
  - 1p19
  - 6c7q
  - 3zso
  - 1ado
  - 6ej2
  - 2i2c
  - 1ai7
  - 6fnq
  - 3kjd
  - 4nl1
  - 4qge
  - 1cnx
  - 5o2d
  - 4u54
  - 6eqv
  - 2e94
  - 3k8c
  - 1ie9
  - 5d2r
  - 2yay
  - 5zo8
  - 5ngz
  - 1a1e
  - 4xmr
  - 6fs1
  - 3zqe
  - 3ove
  - 6hly
  - 2rio
  - 1lah
  - 3ouj
  - 1h2t
  - 4luz
  - 4qpd
  - 4pg9
  - 3ip6
  - 1ew9
  - 6aqs
  - 5yyf
  - 4w9j
  - 6d2o
  - 5xg5
  - 4k0o
  - 2jkh
  - 4urz
  - 3b2q
  - 4pcs
  - 4ew3
  - 6ma4
  - 5n9r
  - 4kyh
  - 3k5x
  - 2xyt
  - 4qpl
  - 1ui0
  - 4jne
  - 4elf
  - 5bw4
  - 4n7u
  - 5uff
  - 4gq4
  - 3dri
  - 3sio
  - 2q6f
  - 1uvt
  - 2vmf
  - 5his
  - 4ucc
  - 6eyt
  - 1mfa
  - 4unp
  - 3pgu
  - 4oma
  - 4bup
  - 1xff
  - 4zgk
  - 3hfb
  - 5l8a
  - 2y80
  - 4np9
  - 3r5t
  - 2bo4
  - 4m6u
  - 3o84
  - 4f1l
  - 1rql
  - 3c8a
  - 1xt8
  - 1kc7
  - 4ysl
  - 5wl0
  - 4myd
  - 5hrx
  - 3r24
  - 5jsg
  - 3ebp
  - 5fyx
  - 5n84
  - 5edl
  - 5tpx
  - 3qps
  - 3usx
  - 5ewa
  - 5w1e
  - 1lrh
  - 5ost
  - 5mby
  - 3lzz
  - 4b5d
  - 5m77
  - 5dq8
  - 4sga

model:
  dropout: 0.2
